# Generated by Django 2.2.1 on 2019-11-17 09:33

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to=classifier.models.path_and_rename)),
                ('category', models.CharField(max_length=3)),
            ],
        ),
    ]
